apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo
    apps.tanzu.vmware.com/workload-type: web
  name: tanzujavawebapp
  namespace: default
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/mgbrodi/tanzu-java-web-app-orig
